# Makefile for osx

BULLET_PATH=../bullet-2.76.mac/src
GLFW_PATH=../glfw/trunk

DEV_CFLAGS = -g -Wall -DELF_PLAYER -DELF_MACOSX
REL_CFLAGS = -Wall -O2 -DELF_PLAYER -DELF_MACOSX

INCS = -Iphy -Igfx -Ielf -I/usr/include/lua5.1 -I/usr/include/freetype2 -I$(BULLET_PATH) \
	-I$(GLFW_PATH)/include -I/opt/local/include/ -I/opt/local/include/freetype2 -framework OpenAL \
	-I/usr/include/malloc

BLENDELF_LIBS = -L/opt/local/lib $(GLFW_PATH)/lib/cocoa/libglfw.a -lGLEW -pthread \
	-lfreeimage -lvorbisfile -lvorbis -logg -llua -lfreetype -lz -lassimp \
	-framework OpenGL -framework OpenAL -lstdc++ -framework Cocoa \
	$(BULLET_PATH)/BulletDynamics/Release/libBulletDynamics.a \
	$(BULLET_PATH)/LinearMath/Release/libLinearMath.a \
	$(BULLET_PATH)/BulletCollision/Release/libBulletCollision.a

all:
	python genwraps.py
	gcc -c elf/blendelf.c $(DEV_CFLAGS) $(INCS)
	gcc -c gfx/gfx.c $(DEV_CFLAGS) $(INCS)
	gcc -c elf/audio.c $(DEV_CFLAGS) $(INCS)
	gcc -c elf/scripting.c $(DEV_CFLAGS) $(INCS)
	g++ -c elf/physics.cpp $(DEV_CFLAGS) $(INCS)
	gcc -c elf/binds.c $(DEV_CFLAGS) $(INCS)
	gcc -Wl -o blendelf *.o $(DEV_CFLAGS) $(BLENDELF_LIBS)
	rm *.o

